name: 💡 Feature Request
description: Suggest a new tutorial or feature
title: '[Feature]: '
labels: ['enhancement', 'needs-review']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Your ideas help make this collection more comprehensive.

  - type: dropdown
    id: type
    attributes:
      label: Request Type
      description: What kind of feature are you requesting?
      options:
        - New Tutorial Topic
        - Improvement to Existing Tutorial
        - Documentation Enhancement
        - Repository Feature
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe your feature request in detail
      placeholder: What would you like to see added or improved?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this feature be useful?
      placeholder: What problem does this solve or what value does it add?
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Possible Implementation
      description: Do you have ideas for how this could be implemented?
      placeholder: Any thoughts on libraries, approaches, or examples?

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Any examples or references that might help?
      placeholder: Links to similar tutorials, papers, or resources

---

