name: Notebook Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-notebooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbformat nbconvert

      - name: Validate notebook format
        run: |
          find . -name "*.ipynb" -exec python -m nbformat.validator {} \;

      - name: Check for execution errors
        run: |
          find . -name "*.ipynb" -exec jupyter nbconvert --to notebook --execute --inplace {} \;

---

